MVC/Telligent.SitecoreSDK.Samples.MVC/Controllers/BlogController.cs
using System.Collections.Specialized;
using System.Globalization;
using System.Web.Mvc;
using Telligent.Evolution.Extensibility.Rest.Version1;
using Telligent.SitecoreSDK.Samples.MVC.Models;
using Telligent.SitecoreSDK.Samples.MVC.Util;

namespace Telligent.SitecoreSDK.Samples.MVC.Controllers
{
    public class BlogController : Controller
    {
        public ActionResult ListBlogs()
        {
            var host = Host.Get("default");
            var parms = new NameValueCollection
            {
                {"PageSize", "50"},
                {"PageIndex", "0"},
                {"SortBy", "LastPost"},
                {"SortOrder", "Descending"}
            };

            var options = new RestGetOptions {QueryStringParameters = parms};
            var response = host.GetToDynamic(2, Endpoints.BlogsJson, true,options );

            return View("ListBlogs", response.Blogs);
        }

        public ActionResult ListPosts(int id)
        {
            var host = Host.Get("default");
            var parms = new NameValueCollection
            {
                {"PageSize", "50"},
                {"PageIndex", "0"},
                {"SortBy", "MostRecent"},
                {"SortOrder", "Descending"}
            };

            var options = new RestGetOptions {QueryStringParameters = parms};
            var pathParameters = new NameValueCollection {{"blogid", id.ToString(CultureInfo.InvariantCulture)}};

            options.PathParameters = pathParameters;

            var response = host.GetToDynamic(2, Endpoints.BlogsPostJson, true, options);

            return View("PostList", response.BlogPosts);
        }

        public ActionResult ShowPost(int blogid, string slug)
        {
            var host = Host.Get("default");

            BlogPostViewModel model = null;

            var postResponse = host.GetToDynamic(2, 
                Endpoints.BlogsPostNameJson, 
                true,
                new RestGetOptions
                {
                    PathParameters = new NameValueCollection
                    {
                        { "blogid", blogid.ToString(CultureInfo.InvariantCulture) }, 
                        { "name", slug }
                    }
                });

            if (postResponse != null)
            {
                model = new BlogPostViewModel(postResponse.BlogPost);
            }

            return View("Post", model);
        }
    }
}

MVC/Telligent.SitecoreSDK.Samples.MVC/Controllers/ForumController.cs
using System;
using System.Collections.Specialized;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Telligent.Evolution.Extensibility.Rest.Version1;
using Telligent.SitecoreSDK.Samples.MVC.Models;
using Telligent.SitecoreSDK.Samples.MVC.Util;

namespace Telligent.SitecoreSDK.Samples.MVC.Controllers
{
    public class ForumController : Controller
    {
        // GET: Forum  Currently a site wide aggregate
        public ActionResult ListForums()
        {
            //If you loaded multiple hosts, like say for each website, replace the string with a retrieval method of your choice.
            //Example, if you loaded by site name you could get the current site name.
            var host = Host.Get("default");

            //When faced with options objects used in platofmr API, you can pass them in as Hashtables with the key being the property
            //and the value
            var options = new NameValueCollection
            {
                {"PageSize", "50"},
                {"PageIndex", "0"},
                {"SortBy", "LastPost"},
                {"SortOrder", "Descending"}
            };

            var endpoint = Endpoints.ForumList + ParseQueryString(options);
            //The third parameter is a params[] argument, it should be the method arguments for the corresponding API.
            //example:  If the API is core_v2_Foo.List(int,string,Options options) then the 3rd parm could be (1,"bar",Hashtable obj)

            var response =host.GetToDynamic(2, endpoint);
           
            return View("ListForums", response.Forums);
        }

        public ActionResult ViewForum(int forumId)
        {
            //If you loaded multiple hosts, like say for each website, replace the string with a retrieval method of your choice.
            //Example, if you loaded by site name you could get the current site name.
            var host = Host.Get("default");

            var endpointForumShow = string.Format(Endpoints.ForumView, forumId);
            dynamic responseForumShow = host.GetToDynamic(2, endpointForumShow);

            ViewBag.ForumName = responseForumShow.Forum.Name;
            ViewBag.ForumId = responseForumShow.Forum.Id;

            var options = new NameValueCollection
            {
                {"PageSize", "50"},
                {"PageIndex", "0"},
                {"SortBy", "LastPost"},
                {"SortOrder", "Descending"}
            };

            var endpointThreadList = string.Format(Endpoints.ThreadsList, forumId,
                String.Join("&", options.AllKeys.Select(a => a + "=" + HttpUtility.UrlEncode(options[a]))));
            dynamic responseThreadList = host.GetToDynamic(2, endpointThreadList);

            return View("ViewForum", responseThreadList.Threads);
        }

        public ActionResult ViewThread(int threadId)
        {
            //If you loaded multiple hosts, like say for each website, replace the string with a retrieval method of your choice.
            //Example, if you loaded by site name you could get the current site name.
            var host = Host.Get("default");

            var endpointThreadShow = string.Format("forums/threads/{0}.json", threadId);
            dynamic responseThreadShow = host.GetToDynamic(2, endpointThreadShow);

            var options = new NameValueCollection();
            options.Add("PageSize", "50");
            options.Add("PageIndex", "0");
            options.Add("SortBy", "PostDate");
            options.Add("SortOrder", "Ascending");

            var endpointForumShow = string.Format("forums/{0}.json", responseThreadShow.Thread.ForumId);
            dynamic responseForumShow = host.GetToDynamic(2, endpointForumShow);

            ViewBag.ForumName = responseForumShow.Forum.Name;
            ViewBag.ForumId = responseForumShow.Forum.Id;

            var endpoint = string.Format("forums/{0}/threads/{1}/replies.json?{2}", responseForumShow.Forum.Id, threadId,
                String.Join("&", options.AllKeys.Select(a => a + "=" + HttpUtility.UrlEncode(options[a]))));
            dynamic response = host.GetToDynamic(2, endpoint);
            if (response.Errors.Count > 0)
                throw new Exception(response.Errors[0].Message.ToString());

            return View("ViewThread", new ForumThreadViewModel(responseThreadShow.Thread, response.Replies));
        }

        public ActionResult CreateReply(int threadId)
        {
            return View(new ForumReplyCreateModel() { ThreadId = threadId });
        }

        [HttpPost]
        public ActionResult CreateReply(ForumReplyCreateModel model)
        {
            if (ModelState.IsValid)
            {
                //If you loaded multiple hosts, like say for each website, replace the string with a retrieval method of your choice.
                //Example, if you loaded by site name you could get the current site name.
                var host = Host.Get("default");

                var path = new NameValueCollection();
                path.Add("ThreadId", model.ThreadId.ToString());
                var post = new NameValueCollection();
                post.Add("Body", model.Body);

                dynamic response = host.PostToDynamic(2, "forums/threads/{ThreadId}/replies.json", true, 
                    new RestPostOptions { PathParameters = path, PostParameters = post });

                return RedirectToAction("ViewThread",new{threadId=model.ThreadId});
            }
            return View(model);
        }

        public ActionResult CreateThread(int forumId)
        {
            return View(new ForumThreadCreateModel() { ForumId = forumId });
        }

        [HttpPost]
        public ActionResult CreateThread(ForumThreadCreateModel model)
        {
            if (ModelState.IsValid)
            {
                //If you loaded multiple hosts, like say for each website, replace the string with a retrieval method of your choice.
                //Example, if you loaded by site name you could get the current site name.
                var host = Host.Get("default");

                var path = new NameValueCollection();
                path.Add("ForumId", model.ForumId.ToString());
                var post = new NameValueCollection();
                post.Add("Subject", model.Subject);
                post.Add("Body", model.Body);

                dynamic response = host.PostToDynamic(2, "forums/{ForumId}/threads.json", true, new RestPostOptions { PathParameters = path, PostParameters = post});

                return RedirectToAction("ViewThread",new {threadId=response.Thread.Id});
            }

            return View(model);
        }

        private string ParseQueryString(NameValueCollection nvc)
        {
            string q = String.Join("&",
              nvc.AllKeys.Select(a => a + "=" + HttpUtility.UrlEncode(nvc[a])));
            return q;
        }
    }
   
}

MVC/Telligent.SitecoreSDK.Samples.MVC/Views/layouts/telligent.cshtml
@using System.Security.Policy
@using Sitecore.Mvc
@using Sitecore.Mvc.Analytics.Extensions
@using Telligent.SitecoreSDK.Samples.MVC
@using Sitecore.Mvc.Presentation

<!DOCTYPE html>
<html>
<head>
  <title>Community Server SDK Sitecore Examples</title>
  @Html.Sitecore().VisitorIdentification()
    <!-- Latest compiled and minified CSS -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    
    <!-- Latest FontAwesome css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    
    <!-- JQuery Star Rating Plugin - Raty 2.7.0 -->
    <script src="~/Content/js/raty.js"></script>
    
    <script src="~/Content/js/samples.js"></script>
    
    <!-- Latest FontAwesome used for likes -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    
    <link href="~/Content/css/site.css" rel="stylesheet" />
</head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">SDK Samples</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        @*
                        <li>@Html.ActionLink("Blogs", "Blog", "ListBlogs")</li>
                        <li>@Html.ActionLink("Forums", "Forum", "ListForums")</li>
                        *@
                        <li><a href="~/mvccommunity/blogs">Blogs</a></li>
                        <li><a href="~/mvccommunity/forums">Forums</a></li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
           @RenderBody()   
        </div>
    </body>
</html>